### ISSUE TITLE
Return paths with consistent separators

### ISSUE THREAD

**Issue by chrisfilo** [grabbles/grabbit#7] opened 2016-08-18 06:57 UTC
Currently grabbit returns paths with some amount of backslashes

`D:/OpenfMRI/ds114_with_dates/sub-08\ses-retest\func\sub-08_ses-retest_task-covertverbgeneration_bold.nii.gz`

instead of:

`D:\OpenfMRI\ds114_with_dates\sub-08\ses-retest\func\sub-08_ses-retest_task-covertverbgeneration_bold.nii.gz`
on Windows
and
`/data/OpenfMRI/ds114_with_dates/sub-08/ses-retest/func/sub-08_ses-retest_task-covertverbgeneration_bold.nii.gz`
on Linux/OS X

**Comment by tyarkoni** [comment] 2016-08-19 00:05
I can't reproduce this; on OS X, I always get forward slashes everywhere (don't have access to a Windows machine). Can you provide more details? What's the query? And is this with the original BIDS json spec, or have there been changes to it? As far as I can tell, there's no hardcoding of separators anywhere; they're always manipulated through os.path. So I'm not sure how this would happen.

**Comment by tyarkoni** [comment] 2017-03-04 21:38
Can we close this, or is this still an issue, @chrisfilo?

**Closed** 2017-03-04 21:44 UTC
